# Generated by Django 5.1.3 on 2024-11-12 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=300)),
                ('house_name', models.CharField(max_length=100)),
                ('door_code', models.CharField(max_length=50)),
                ('gate_code', models.CharField(max_length=50)),
                ('community_pool', models.CharField(max_length=50)),
                ('fitness_center', models.CharField(blank=True, max_length=50, null=True)),
                ('wifi_network', models.CharField(blank=True, max_length=100, null=True)),
                ('wifi_password', models.CharField(blank=True, max_length=100, null=True)),
                ('who_cares', models.CharField(max_length=50)),
                ('observations', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
